<?php

class idImageIndexedUpdateProcessor extends modObjectUpdateProcessor
{
    public $objectType = 'idImageIndexed';
    public $classKey = 'idImageIndexed';
    public $languageTopics = ['idimage:manager'];
    public $permission = 'save';

    public idImage $idImage;

    public function initialize()
    {
        $this->idImage = $this->modx->getService('idimage', 'idImage', MODX_CORE_PATH.'components/idimage/model/');

        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * We doing special check of permission
     * because of our objects is not an instances of modAccessibleObject
     *
     * @return bool|string
     */
    public function beforeSave()
    {
        if (!$this->checkPermissions()) {
            return $this->modx->lexicon('access_denied');
        }

        return true;
    }


    /**
     * @return bool
     */
    public function beforeSet()
    {
        $id = (int)$this->getProperty('id');
        $pid = trim($this->getProperty('pid'));
        if (empty($id)) {
            return $this->modx->lexicon('idimage_item_err_ns');
        }

        if (empty($pid)) {
            $this->modx->error->addField('pid', $this->modx->lexicon('idimage_item_err_pid'));
        } elseif ($this->modx->getCount($this->classKey, ['pid' => $pid, 'id:!=' => $id])) {
            $this->modx->error->addField('pid', $this->modx->lexicon('idimage_item_err_ae'));
        }

        return parent::beforeSet();
    }
}

return 'idImageIndexedUpdateProcessor';
