<?php
/**
 * Created by Andrey Stepanenko.
 * User: webnitros
 * Date: 22.03.2025
 * Time: 12:45
 */

namespace IdImage\Command;


use IdImage\Abstracts\CommandAbstract;
use IdImage\Interfaces\CommandInterfaces;

class UploadCommand extends CommandAbstract implements CommandInterfaces
{
    protected ?string $operation = \IdImage\Sender::OPERATION_UPLOAD;

    public function handle(int $i, array $ids): bool
    {
        return parent::handleTask($i, $ids); // TODO: Change the autogenerated stub
    }
}
