<?php

use IdImage\TaskCollection;

if (!class_exists('idImageActionsTaskSendProcessor')) {
    include_once __DIR__.'/send.class.php';
}

class idImageActionsTaskUploadProcessor extends idImageActionsTaskSendProcessor
{

    public function initialize()
    {
        $this->setProperty('operation', \IdImage\Sender::OPERATION_UPLOAD);

        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function stepChunk()
    {
        return $this->idImage->limitUpload();
    }

}

return 'idImageActionsTaskUploadProcessor';
